### ISSUE TITLE
Plugin crashes site

### ISSUE THREAD

**Issue by MeanderingCode** [RocketChat/WordPressPlugin#7] opened 2016-05-31 22:06 UTC
The plugin kills the site, erroring out attempting to call a nonexistant fucntion `$this->_process_formData()`

WordPress debug log:

`[31-May-2016 20:35:44 UTC] PHP Fatal error: Call to undefined method RocketChat_LIVEChat::_process_formData() in /home/user/www/wp-content/plugins/rocketchat-livechat/livechat-wordpress.php on line 339`

**Comment by tikmaster** [comment] 2016-06-15 21:02
15 days later, still the same issue. Any solutions ?

**Comment by engelgabriel** [comment] 2016-06-15 23:14
Duplicate of #10 ?

**Comment by mbanusic** [comment] 2016-08-15 08:48
Plugin at the master branch doesn't work, new one in the develop branch works. We will later move  to the master as development progresses

**Closed as completed by mbanusic** 2016-08-15 08:48 UTC
